services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    image: "harbor.cybertech.com.vn/livekit-dev-duong/apiserver-tts-custom:v1"
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./voices:/home/nonroot/tts_server/voices

  agent:
    build:
      context: .
      dockerfile: docker/styletts2/Dockerfile.agent
    image: "harbor.cybertech.com.vn/livekit-dev-duong/livekit-agent:v1"
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    env_file:
      - .env
    environment:
      - STYLETTS2_API_URL=http://api:5050
    depends_on:
      - styletts2-service
