version: "3.8"

x-logging: &default-logging
  options:
    max-size: "10m"
    max-file: "3"
  driver: json-file

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
      args:
        - UID=${UID:-10001}
    image: "harbor.cybertech.com.vn/livekit-dev-duong/apiserver-tts-custom:v1"
    restart: unless-stopped
    ports:
      - "${API_PORT:-5050}:5050"
    volumes:
      - ./voices:/app/voices:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G
        reservations:
          cpus: "0.5"
          memory: 1G
    logging: *default-logging

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
